version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static # Persist uploaded files
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
